name = "Terse"
uuid = "913af9f3-6a3d-46e7-8a90-1058e86354fb"
version = "0.2.3"
authors = ["Josh Day <emailjoshday@gmail.com>"]

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
