project:
  type: book
  output-dir: _site

engines: ['julia']
julia:
  project: "."

book:
  title: "Terse.jl"
  search:
    location: sidebar
    keyboard-shortcut:
      - "/"
  navbar:
    logo: assets/logo.svg
    logo-href: https://rallypoint1.com
    right:
      - icon: star
        href: https://github.com/RallypointOne/Terse.jl/stargazers
        text: "Star"
      - icon: github
        href: https://github.com/RallypointOne/Terse.jl
  chapters:
    - part: "Docs"
      chapters:
        - index.qmd
        - pages/getting-started.qmd
        - pages/comparison.qmd
    - part: "API"
      chapters:
        - pages/api.qmd
    - part: "Resources"
      chapters:
        - pages/changelog.qmd
        - pages/coverage.qmd

  page-footer:
    center: "Built on 2026-02-23"

language:
  search-text-placeholder: "Search  (/)"

format:
  html:
    css: assets/styles.css
    number-sections: false
    theme:
      - flatly
      - assets/theme.scss
    include-after-body:
      - file: assets/_version-selector.html
