# Copy the LocalCoverage HTML report generated by resources/coverage.qmd into the
# rendered site so the coverage page's <iframe src="coverage/index.html"> resolves.
# Runs as a Quarto post-render step (after Quarto has copied its own resources),
# so the generated report directory is guaranteed to exist by this point.

src = joinpath("resources", "coverage")
dest = joinpath(get(ENV, "QUARTO_PROJECT_OUTPUT_DIR", "_site"), "resources", "coverage")

if isdir(src)
    rm(dest; recursive=true, force=true)
    mkpath(dirname(dest))
    cp(src, dest)
    println("Copied coverage report to $dest")
else
    @warn "No coverage report at $src; skipping"
end
