module Terse

export @types

const _MUTABLE_SYM = Symbol("@mutable")
const _CONST_SYM   = Symbol("@const")
const _ESC_SYM     = Symbol("@esc")
const _HIDE_SYM    = Symbol("@hide")

#-----------------------------------------------------------------------------# autoshow
# Trait: returns true for types generated by @types (overloaded in macro expansion).
is_terse_type(::Type{T}) where {T} = false
is_terse_type(types::Tuple) = map(is_terse_type, types)

# Trait: returns tuple of field names hidden from `autoshow` (overloaded in macro expansion).
hidden_fields(::Type{T}) where {T} = ()

# Print `x` as `TypeName{params...}(field=val, ...)`, abbreviating nested terse types.
function autoshow(io::IO, x::T, compact::Bool = false) where {T}
    print(io, T.name.name)
    isempty(T.parameters) || print(io, '{', join(T.parameters, ", "), '}')
    fields = fieldnames(T)
    hidden = hidden_fields(T)
    n_visible = count(f -> f ∉ hidden, fields)
    n_visible == 0 && return
    compact && return print(io, "(…)")
    print(io, '(')
    k = 0
    for (i, field) in enumerate(fields)
        field ∈ hidden && continue
        k += 1
        k > 1 && print(io, ", ")
        val = getfield(x, field)
        print(io, field, '=')
        is_terse_type(fieldtypes(T))[i] ? autoshow(io, val, true) : show(io, val)
    end
    print(io, ')')
end


# Generate `is_terse_type`, `Base.show`, and optionally `hidden_fields` method exprs.
function _show_method_exprs(name, hidden=Symbol[])
    is_terse = GlobalRef(Terse, :is_terse_type)
    autoshow = GlobalRef(Terse, :autoshow)
    base_show = GlobalRef(Base, :show)
    type_pat = Expr(:(::), Expr(:curly, :Type, Expr(:(<:), name)))
    trait_expr = Expr(:(=), Expr(:call, is_terse, type_pat), true)
    show_expr = Expr(:(=), Expr(:call, base_show, Expr(:(::), :io, :IO), Expr(:(::), :x, name)),
        Expr(:call, autoshow, :io, :x))
    result = [trait_expr, show_expr]
    if !isempty(hidden)
        hidden_ref = GlobalRef(Terse, :hidden_fields)
        hidden_expr = Expr(:(=), Expr(:call, hidden_ref, type_pat),
            Expr(:tuple, QuoteNode.(hidden)...))
        push!(result, hidden_expr)
    end
    return result
end

#-----------------------------------------------------------------------------# computed constructors
# Unwrap a :block wrapper from short-form function syntax: `f(x) = y` parses RHS as Expr(:block, LineNumberNode, y).
_unwrap_block(ex) = Meta.isexpr(ex, :block) ? ex.args[end] : ex
# Check if an expression is a computed constructor: `Name(args...) = new(field = expr, ...)`.
_is_computed_ctor(ex) = Meta.isexpr(ex, :(=)) && (rhs = _unwrap_block(ex.args[2]); Meta.isexpr(rhs, :call) && rhs.args[1] === :new)

# Build a struct with a custom constructor from `Name(args...) = new(field::T = expr, ...)`.
function _make_computed_struct(is_mutable, sig, ctor_args, new_fields)
    all(f -> Meta.isexpr(f, :kw), new_fields) ||
        error("@types: every argument to `new(...)` must be `field = expr` or `field::T = expr`")
    ctor = _ctor_name(sig)
    struct_fields = map(f -> f.args[1], new_fields)
    field_values  = map(f -> f.args[2], new_fields)
    params = _sig_params(sig)
    param_names = map(_param_name, params)
    if isempty(params)
        new_call = Expr(:call, :new, field_values...)
        ctor_def = Expr(:(=), Expr(:call, ctor, ctor_args...), new_call)
        return Expr(:struct, is_mutable, sig, Expr(:block, struct_fields..., ctor_def))
    else
        struct_expr = Expr(:struct, is_mutable, sig, Expr(:block, struct_fields...))
        ctor_call = Expr(:call, Expr(:curly, ctor, param_names...), field_values...)
        outer = Expr(:(=), Expr(:where, Expr(:call, ctor, ctor_args...), param_names...), ctor_call)
        return Expr(:block, struct_expr, outer)
    end
end

#-----------------------------------------------------------------------------# @types helpers
# Check if a field expr is wrapped in @hide(...).
_is_hidden_field(f) = Meta.isexpr(f, :macrocall) && f.args[1] === _HIDE_SYM
# Strip the @hide wrapper, returning the inner field expr.
_unwrap_hidden(f)   = _is_hidden_field(f) ? f.args[end] : f

# Strip @hide from fields, returning (stripped_fields, hidden_names).
function _strip_hidden(fields)
    hidden = Symbol[]
    stripped = map(fields) do f
        if _is_hidden_field(f)
            inner = f.args[end]
            push!(hidden, _fname(_plain(_unwrap_const(inner))))
            return inner
        elseif Meta.isexpr(f, :kw) && _is_hidden_field(f.args[1])
            inner = f.args[1].args[end]
            push!(hidden, _fname(_plain(_unwrap_const(inner))))
            return Expr(:kw, inner, f.args[2])
        end
        return f
    end
    stripped, hidden
end

# Check if a field expr is wrapped in @const(...).
_is_const_field(f) = Meta.isexpr(f, :macrocall) && f.args[1] === _CONST_SYM
# Strip the @const wrapper, returning the inner field expr.
_unwrap_const(f)   = _is_const_field(f) ? f.args[end] : f

# Convert a field expr to a struct body field, adding `const` if wrapped in @const.
function _to_struct_field(f)
    _is_const_field(f) && return Expr(:const, _plain(f.args[end]))
    return _plain(f)
end

# Parse `Name` or `Name{T,...}` into (name, params).
function _terse_parse_type(ex)
    ex isa Symbol && return ex, Any[]
    Meta.isexpr(ex, :curly) && return ex.args[1], ex.args[2:end]
    error("@types: invalid type expression: $ex")
end

# Extract type parameters from a struct signature (unwrapping `<:`).
_sig_params(sig) = (inner = Meta.isexpr(sig, :<:) ? sig.args[1] : sig;
    Meta.isexpr(inner, :curly) ? inner.args[2:end] : Any[])
# Strip bounds from a type parameter: `T <: Integer` → `T`.
_param_name(p) = Meta.isexpr(p, :<:) ? p.args[1] : p

# Parse `Name(fields...; kw_fields...)` into (name, params, pos_fields, kw_fields).
function _terse_parse_subtype(ex)
    Meta.isexpr(ex, :call) || error("@types: expected `TypeName(fields...)`, got: $ex")
    name, params = _terse_parse_type(ex.args[1])
    rest = ex.args[2:end]
    if !isempty(rest) && Meta.isexpr(rest[1], :parameters)
        return name, params, rest[2:end], rest[1].args
    else
        return name, params, rest, Any[]
    end
end

# Extract the constructor name from a struct signature (unwrapping `<:` and `{}`).
_ctor_name(sig) = Meta.isexpr(sig, :<:) ? _ctor_name(sig.args[1]) : (Meta.isexpr(sig, :curly) ? sig.args[1] : sig)
# Strip default value from a field expr: `x::T = val` → `x::T`.
_plain(f) = Meta.isexpr(f, :kw) ? f.args[1] : f
# Extract the field name from a typed or untyped field expr.
_fname(f) = Meta.isexpr(f, :(::)) ? f.args[1] : f
# Build `Name{params...}` or just `Name` if params is empty.
_build_curly(name, params) = isempty(params) ? name : Expr(:curly, name, params...)
# Check if an expression is a string literal (used to detect user docstrings).
_is_docstr(ex) = ex isa AbstractString || Meta.isexpr(ex, :string)

# Pretty-print a field/type expression as a string for auto-generated docstrings.
function _expr_to_str(ex)
    ex isa Symbol && return string(ex)
    ex isa Number && return string(ex)
    ex isa AbstractString && return repr(ex)
    Meta.isexpr(ex, :(::)) && return _expr_to_str(ex.args[1]) * "::" * _expr_to_str(ex.args[2])
    Meta.isexpr(ex, :kw) && return _expr_to_str(ex.args[1]) * " = " * _expr_to_str(ex.args[2])
    Meta.isexpr(ex, :<:) && return _expr_to_str(ex.args[1]) * " <: " * _expr_to_str(ex.args[2])
    Meta.isexpr(ex, :curly) && return _expr_to_str(ex.args[1]) * "{" * join(_expr_to_str.(ex.args[2:end]), ", ") * "}"
    return string(ex)
end

# Build the constructor signature string for auto-generated docstrings.
function _autodoc_sig(name, params, pos_fields, kw_fields)
    name_str = isempty(params) ? string(name) : string(name) * "{" * join(_expr_to_str.(params), ", ") * "}"
    isempty(pos_fields) && isempty(kw_fields) && return name_str
    pos_strs = _expr_to_str.(_unwrap_const.(pos_fields))
    isempty(kw_fields) && return name_str * "(" * join(pos_strs, ", ") * ")"
    kw_strs = _expr_to_str.(_unwrap_const.(kw_fields))
    pfx = isempty(pos_strs) ? "" : join(pos_strs, ", ") * "; "
    return name_str * "(" * pfx * join(kw_strs, ", ") * ")"
end

# Wrap an expression with a @doc call to attach a docstring.
_wrap_doc(doc, ex) = Expr(:macrocall, GlobalRef(Core, Symbol("@doc")), LineNumberNode(0, :none), doc, ex)

# If the expression is a `@mutable` macrocall, return (true, unwrapped_expr).
function _unwrap_mutable(is_mutable, ex)
    Meta.isexpr(ex, :macrocall) && ex.args[1] === _MUTABLE_SYM || return is_mutable, ex
    return true, ex.args[end]
end

# Split a _make_struct result into (struct_expr, outer_ctors...).
_split_struct(ex) = Meta.isexpr(ex, :block) && Meta.isexpr(ex.args[1], :struct) ?
    (ex.args[1], ex.args[2:end]) : (ex, Any[])

# Build a struct Expr with optional inner constructors for defaults/keyword args.
function _make_struct(is_mutable, sig, pos_fields, kw_fields=Any[])
    has_const = any(_is_const_field, pos_fields) || any(_is_const_field, kw_fields)
    has_const && !is_mutable &&
        error("@types: @const fields are only valid inside a @mutable (or `@types mutable`) type")

    has_pos_defaults = any(f -> Meta.isexpr(_unwrap_const(f), :kw), pos_fields)
    has_explicit_kw  = !isempty(kw_fields)

    plain_pos  = map(f -> _plain(_unwrap_const(f)), pos_fields)
    plain_kw   = map(f -> _plain(_unwrap_const(f)), kw_fields)
    all_names  = map(_fname, [plain_pos; plain_kw])
    ctor       = _ctor_name(sig)
    struct_pos = map(_to_struct_field, pos_fields)
    struct_kw  = map(_to_struct_field, kw_fields)

    !has_pos_defaults && !has_explicit_kw &&
        return Expr(:struct, is_mutable, sig, Expr(:block, struct_pos...))

    params = _sig_params(sig)
    param_names = map(_param_name, params)

    if !isempty(params)
        # Parametric types: use outer constructors so type params are inferred.
        struct_expr = Expr(:struct, is_mutable, sig, Expr(:block, [struct_pos; struct_kw]...))
        ctor_full = Expr(:curly, ctor, param_names...)
        ctor_call = Expr(:call, ctor_full, all_names...)
        if has_explicit_kw
            call_sig = Expr(:call, ctor, Expr(:parameters, map(_unwrap_const, kw_fields)...), map(_unwrap_const, pos_fields)...)
            outer = Expr(:(=), Expr(:where, call_sig, param_names...), ctor_call)
            return Expr(:block, struct_expr, outer)
        else
            required = filter(f -> !Meta.isexpr(_unwrap_const(f), :kw), pos_fields)
            optional = filter(f ->  Meta.isexpr(_unwrap_const(f), :kw), pos_fields)
            pos_sig = Expr(:call, ctor, map(_unwrap_const, pos_fields)...)
            pos_outer = Expr(:(=), Expr(:where, pos_sig, param_names...), ctor_call)
            kw_sig = Expr(:call, ctor, Expr(:parameters, map(_unwrap_const, optional)...), map(_unwrap_const, required)...)
            kw_outer = Expr(:(=), Expr(:where, kw_sig, param_names...), ctor_call)
            return Expr(:block, struct_expr, pos_outer, kw_outer)
        end
    end

    new_call = Expr(:call, :new, all_names...)
    if has_explicit_kw
        ctor_def = Expr(:(=),
            Expr(:call, ctor, Expr(:parameters, map(_unwrap_const, kw_fields)...), map(_unwrap_const, pos_fields)...),
            new_call)
        return Expr(:struct, is_mutable, sig, Expr(:block, [struct_pos; struct_kw]..., ctor_def))
    else
        required = filter(f -> !Meta.isexpr(_unwrap_const(f), :kw), pos_fields)
        optional = filter(f ->  Meta.isexpr(_unwrap_const(f), :kw), pos_fields)
        pos_ctor = Expr(:(=), Expr(:call, ctor, map(_unwrap_const, pos_fields)...), new_call)
        kw_ctor  = Expr(:(=),
            Expr(:call, ctor, Expr(:parameters, map(_unwrap_const, required)..., map(_unwrap_const, optional)...)),
            new_call)
        return Expr(:struct, is_mutable, sig, Expr(:block, struct_pos..., pos_ctor, kw_ctor))
    end
end

# Check if `name` is already an abstract type in `mod`.
function _is_existing_abstract(mod, name)
    isdefined(mod, name) || return false
    T = getfield(mod, name)
    T isa Type || error("@types: `$name` exists but is not a type")
    isabstracttype(T) || error("@types: `$name` is a concrete type; cannot add subtypes")
    return true
end

# Recursively generate abstract type + concrete subtypes for a `Parent > (children...)` hierarchy.
function _types_impl(mod, abstract_expr, subtypes_expr, parent_head=nothing; is_mutable=false, docpath="")
    abstract_name, abstract_params = _terse_parse_type(abstract_expr)
    abstract_head = _build_curly(abstract_name, abstract_params)
    existing = _is_existing_abstract(mod, abstract_name)
    abstract_decl = existing ? nothing : Expr(:abstract, parent_head === nothing ? abstract_head : Expr(:<:, abstract_head, parent_head))
    current_path = isempty(docpath) ? string(abstract_name) : docpath * " > " * string(abstract_name)

    children = Meta.isexpr(subtypes_expr, :tuple) ? subtypes_expr.args : [subtypes_expr]

    decls = Any[]
    pending_doc = nothing
    for st in children
        if _is_docstr(st)
            pending_doc = st
            continue
        end
        if Meta.isexpr(st, :macrocall) && st.args[1] === _ESC_SYM
            push!(decls, st.args[end])
            continue
        end
        local_mutable, st = _unwrap_mutable(is_mutable, st)
        if _is_computed_ctor(st)
            ctor_expr, new_call = st.args[1], _unwrap_block(st.args[2])
            name, params = _terse_parse_type(ctor_expr.args[1])
            ctor_args = ctor_expr.args[2:end]
            new_fields = new_call.args[2:end]
            result = _make_computed_struct(local_mutable, Expr(:<:, _build_curly(name, params), abstract_head), ctor_args, new_fields)
            s, outer = _split_struct(result)
            doc = something(pending_doc, current_path * " > \n" * _autodoc_sig(name, params, ctor_args, Any[]))
            push!(decls, _wrap_doc(doc, s))
            append!(decls, outer)
            append!(decls, _show_method_exprs(name))
            pending_doc = nothing
        elseif Meta.isexpr(st, :call) && st.args[1] == :>
            push!(decls, _types_impl(mod, st.args[2], st.args[3], abstract_head; is_mutable=local_mutable, docpath=current_path))
            pending_doc = nothing
        elseif st isa Symbol || Meta.isexpr(st, :curly)
            name, params = _terse_parse_type(st)
            params = isempty(params) ? abstract_params : params
            result = _make_struct(local_mutable, Expr(:<:, _build_curly(name, params), abstract_head), Any[])
            s, outer = _split_struct(result)
            doc = something(pending_doc, current_path * " > \n" * _autodoc_sig(name, params, Any[], Any[]))
            push!(decls, _wrap_doc(doc, s))
            append!(decls, outer)
            append!(decls, _show_method_exprs(name))
            pending_doc = nothing
        else
            name, params, pos_fields, kw_fields = _terse_parse_subtype(st)
            pos_fields, hidden_pos = _strip_hidden(pos_fields)
            kw_fields, hidden_kw = _strip_hidden(kw_fields)
            hidden = [hidden_pos; hidden_kw]
            result = _make_struct(local_mutable, Expr(:<:, _build_curly(name, params), abstract_head), pos_fields, kw_fields)
            s, outer = _split_struct(result)
            doc = something(pending_doc, current_path * " > \n" * _autodoc_sig(name, params, pos_fields, kw_fields))
            push!(decls, _wrap_doc(doc, s))
            append!(decls, outer)
            append!(decls, _show_method_exprs(name, hidden))
            pending_doc = nothing
        end
    end

    is_terse = GlobalRef(Terse, :is_terse_type)
    abstract_trait = Expr(:(=), Expr(:call, is_terse, Expr(:(::), Expr(:curly, :Type, Expr(:(<:), abstract_name)))), true)
    preamble = existing ? [abstract_trait] : [abstract_decl, abstract_trait]
    return Expr(:block, preamble..., decls...)
end

# Top-level dispatch: route a single @types expression to the appropriate code generator.
function _types_single(mod, is_mutable, ex)
    is_mutable, ex = _unwrap_mutable(is_mutable, ex)
    if _is_computed_ctor(ex)
        lhs, new_call = ex.args[1], _unwrap_block(ex.args[2])
        new_fields = new_call.args[2:end]
        if Meta.isexpr(lhs, :<:)
            ctor_expr, parent = lhs.args
            name, params = _terse_parse_type(ctor_expr.args[1])
            ctor_args = ctor_expr.args[2:end]
            sig = Expr(:<:, _build_curly(name, params), parent)
        else
            name, params = _terse_parse_type(lhs.args[1])
            ctor_args = lhs.args[2:end]
            sig = _build_curly(name, params)
        end
        result = _make_computed_struct(is_mutable, sig, ctor_args, new_fields)
        s, outer = _split_struct(result)
        return Expr(:block, s, outer..., _show_method_exprs(name)...)
    elseif ex isa Symbol || Meta.isexpr(ex, :curly)
        abstract_name, abstract_params = _terse_parse_type(ex)
        return Expr(:abstract, _build_curly(abstract_name, abstract_params))
    elseif Meta.isexpr(ex, :call) && ex.args[1] != :>
        name, params, pos_fields, kw_fields = _terse_parse_subtype(ex)
        pos_fields, hidden_pos = _strip_hidden(pos_fields)
        kw_fields, hidden_kw = _strip_hidden(kw_fields)
        hidden = [hidden_pos; hidden_kw]
        struct_expr = _make_struct(is_mutable, _build_curly(name, params), pos_fields, kw_fields)
        return Expr(:block, struct_expr, _show_method_exprs(name, hidden)...)
    elseif Meta.isexpr(ex, :<:)
        name, params, pos_fields, kw_fields = _terse_parse_subtype(ex.args[1])
        pos_fields, hidden_pos = _strip_hidden(pos_fields)
        kw_fields, hidden_kw = _strip_hidden(kw_fields)
        hidden = [hidden_pos; hidden_kw]
        struct_expr = _make_struct(is_mutable, Expr(:<:, _build_curly(name, params), ex.args[2]), pos_fields, kw_fields)
        return Expr(:block, struct_expr, _show_method_exprs(name, hidden)...)
    elseif Meta.isexpr(ex, :call) && ex.args[1] == :>
        return _types_impl(mod, ex.args[2], ex.args[3]; is_mutable)
    end
    error("@types: unrecognised syntax: $ex")
end

#-----------------------------------------------------------------------------# @types
"""
    @types AbstractType
    @types [mutable] ConcreteType(pos_fields...; kw_fields...)
    @types [mutable] ConcreteType(pos_fields...; kw_fields...) <: SuperType
    @types [mutable] ConcreteType(args...) = new(field::T = expr, ...)
    @types [mutable] AbstractType > (Subtype1(fields...), Subtype2(fields...))
    @types [mutable] AbstractType{T} > (Subtype1{T}(fields...), Subtype2{T, S}(fields...))

Define abstract types, concrete structs, or full type hierarchies in one expression.

- `mutable` makes all generated concrete structs mutable.
- `@mutable SubType(...)` makes an individual subtype mutable within a hierarchy.
- `@const(field::T)` marks a field as const within a `@mutable` or `mutable` type.
- Fields with default values (`field::T = val`) generate inner constructors for both
  positional-with-defaults and keyword argument construction.
- Use `;` to separate positional fields from keyword-only fields, generating a single
  constructor that mirrors the exact positional/keyword split you specify.
- Subtypes can themselves use `>` to define nested hierarchies.
- Bare names (no parentheses) produce zero-field structs inheriting the parent's type parameters.
- `@hide(field::T)` suppresses a field from the auto-generated `show` method.
- Computed constructors (`Name(args...) = new(field::T = expr, ...)`) let you define struct
  fields that differ from the constructor arguments. Each `new(...)` argument must be
  `field = expr` or `field::T = expr`, where `expr` computes the stored value from the
  constructor args.
- `@esc(expr)` splices arbitrary code (e.g. interface methods) into the hierarchy output.
- Each concrete subtype gets an auto-generated docstring showing its hierarchy path and
  constructor signature (e.g. `"Animal > \nDog(name::String)"`). Place a string literal
  immediately before a subtype entry to override it with a custom docstring.

### Examples

```julia
@types Animal

@types Cat(lives::Int)

@types Dog(name::String) <: Animal

@types mutable Counter(n::Int = 0)

@types Server(host::String; port::Int = 8080, timeout::Int = 30)

@types Animal > (
    Cat(lives::Int),
    Dog(name::String)
)

@types Animal > (
    Cat(lives::Int = 9),
    @mutable Dog(@const(name::String), legs::Int)
)

# Custom docstrings: place a string before the entry to override the auto-generated doc
@types Animal > (
    "A feline with a fixed number of lives.",
    Cat(lives::Int = 9),
    Dog(name::String),  # auto-doc: "Animal > \nDog(name::String)"
)

# Computed constructor: struct fields differ from constructor args
@types Point(x, y) = new(r::Float64 = hypot(x, y), θ::Float64 = atan(y, x))

@types Animal{T} > (
    Cat{T}(lives::Int, family::T),
    Dog{T, S <: AbstractString}(name::S, family::T),
    Invertebrate{T} > (
        Worm,
        Insect{T, I <: Integer}(legs::I, family::T)
    )
)
```
"""
macro types(ex)
    esc(_types_single(__module__, false, ex))
end

macro types(mutable_kw, ex)
    mutable_kw === :mutable || error("@types: expected `mutable`, got `$mutable_kw`")
    esc(_types_single(__module__, true, ex))
end

end # module
