module Terse

export @types

const _MUTABLE_SYM = Symbol("@mutable")
const _CONST_SYM   = Symbol("@const")

#-----------------------------------------------------------------------------# autoshow
# Trait: returns true for types generated by @types (overloaded in macro expansion).
is_terse_type(::Type{T}) where {T} = false
is_terse_type(types::Tuple) = map(is_terse_type, types)

# Print `x` as `TypeName{params...}(field=val, ...)`, abbreviating nested terse types.
function autoshow(io::IO, x::T, compact::Bool = false) where {T}
    print(io, T.name.name)
    isempty(T.parameters) || print(io, '{', join(T.parameters, ", "), '}')
    fields = fieldnames(T)
    if !isempty(fields)
        compact && return print(io, "(…)")
        print(io, '(')
        for (i, field) in enumerate(fields)
            val = getfield(x, field)
            i > 1 && print(io, ", ")
            print(io, field, '=')
            is_terse_type(fieldtypes(T))[i] ? autoshow(io, val, true) : show(io, val)
        end
        print(io, ')')
    end
end


# Generate `is_terse_type` and `Base.show` method exprs for a concrete type name.
function _show_method_exprs(name)
    is_terse = GlobalRef(Terse, :is_terse_type)
    autoshow = GlobalRef(Terse, :autoshow)
    base_show = GlobalRef(Base, :show)
    trait_expr = Expr(:(=), Expr(:call, is_terse, Expr(:(::), Expr(:curly, :Type, Expr(:(<:), name)))), true)
    show_expr = Expr(:(=), Expr(:call, base_show, Expr(:(::), :io, :IO), Expr(:(::), :x, name)),
        Expr(:call, autoshow, :io, :x))
    return [trait_expr, show_expr]
end

#-----------------------------------------------------------------------------# @types helpers
# Check if a field expr is wrapped in @const(...).
_is_const_field(f) = Meta.isexpr(f, :macrocall) && f.args[1] === _CONST_SYM
# Strip the @const wrapper, returning the inner field expr.
_unwrap_const(f)   = _is_const_field(f) ? f.args[end] : f

# Convert a field expr to a struct body field, adding `const` if wrapped in @const.
function _to_struct_field(f)
    _is_const_field(f) && return Expr(:const, _plain(f.args[end]))
    return _plain(f)
end

# Parse `Name` or `Name{T,...}` into (name, params).
function _terse_parse_type(ex)
    ex isa Symbol && return ex, Any[]
    Meta.isexpr(ex, :curly) && return ex.args[1], ex.args[2:end]
    error("@types: invalid type expression: $ex")
end

# Parse `Name(fields...; kw_fields...)` into (name, params, pos_fields, kw_fields).
function _terse_parse_subtype(ex)
    Meta.isexpr(ex, :call) || error("@types: expected `TypeName(fields...)`, got: $ex")
    name, params = _terse_parse_type(ex.args[1])
    rest = ex.args[2:end]
    if !isempty(rest) && Meta.isexpr(rest[1], :parameters)
        return name, params, rest[2:end], rest[1].args
    else
        return name, params, rest, Any[]
    end
end

# Extract the constructor name from a struct signature (unwrapping `<:` and `{}`).
_ctor_name(sig) = Meta.isexpr(sig, :<:) ? _ctor_name(sig.args[1]) : (Meta.isexpr(sig, :curly) ? sig.args[1] : sig)
# Strip default value from a field expr: `x::T = val` → `x::T`.
_plain(f) = Meta.isexpr(f, :kw) ? f.args[1] : f
# Extract the field name from a typed or untyped field expr.
_fname(f) = Meta.isexpr(f, :(::)) ? f.args[1] : f
# Build `Name{params...}` or just `Name` if params is empty.
_build_curly(name, params) = isempty(params) ? name : Expr(:curly, name, params...)
# Check if an expression is a string literal (used to detect user docstrings).
_is_docstr(ex) = ex isa AbstractString || Meta.isexpr(ex, :string)

# Pretty-print a field/type expression as a string for auto-generated docstrings.
function _expr_to_str(ex)
    ex isa Symbol && return string(ex)
    ex isa Number && return string(ex)
    ex isa AbstractString && return repr(ex)
    Meta.isexpr(ex, :(::)) && return _expr_to_str(ex.args[1]) * "::" * _expr_to_str(ex.args[2])
    Meta.isexpr(ex, :kw) && return _expr_to_str(ex.args[1]) * " = " * _expr_to_str(ex.args[2])
    Meta.isexpr(ex, :<:) && return _expr_to_str(ex.args[1]) * " <: " * _expr_to_str(ex.args[2])
    Meta.isexpr(ex, :curly) && return _expr_to_str(ex.args[1]) * "{" * join(_expr_to_str.(ex.args[2:end]), ", ") * "}"
    return string(ex)
end

# Build the constructor signature string for auto-generated docstrings.
function _autodoc_sig(name, params, pos_fields, kw_fields)
    name_str = isempty(params) ? string(name) : string(name) * "{" * join(_expr_to_str.(params), ", ") * "}"
    isempty(pos_fields) && isempty(kw_fields) && return name_str
    pos_strs = _expr_to_str.(_unwrap_const.(pos_fields))
    isempty(kw_fields) && return name_str * "(" * join(pos_strs, ", ") * ")"
    kw_strs = _expr_to_str.(_unwrap_const.(kw_fields))
    pfx = isempty(pos_strs) ? "" : join(pos_strs, ", ") * "; "
    return name_str * "(" * pfx * join(kw_strs, ", ") * ")"
end

# Wrap an expression with a @doc call to attach a docstring.
_wrap_doc(doc, ex) = Expr(:macrocall, GlobalRef(Core, Symbol("@doc")), LineNumberNode(0, :none), doc, ex)

# If the expression is a `@mutable` macrocall, return (true, unwrapped_expr).
function _unwrap_mutable(is_mutable, ex)
    Meta.isexpr(ex, :macrocall) && ex.args[1] === _MUTABLE_SYM || return is_mutable, ex
    return true, ex.args[end]
end

# Build a struct Expr with optional inner constructors for defaults/keyword args.
function _make_struct(is_mutable, sig, pos_fields, kw_fields=Any[])
    has_const = any(_is_const_field, pos_fields) || any(_is_const_field, kw_fields)
    has_const && !is_mutable &&
        error("@types: @const fields are only valid inside a @mutable (or `@types mutable`) type")

    has_pos_defaults = any(f -> Meta.isexpr(_unwrap_const(f), :kw), pos_fields)
    has_explicit_kw  = !isempty(kw_fields)

    plain_pos  = map(f -> _plain(_unwrap_const(f)), pos_fields)
    plain_kw   = map(f -> _plain(_unwrap_const(f)), kw_fields)
    all_names  = map(_fname, [plain_pos; plain_kw])
    ctor       = _ctor_name(sig)
    struct_pos = map(_to_struct_field, pos_fields)
    struct_kw  = map(_to_struct_field, kw_fields)

    !has_pos_defaults && !has_explicit_kw &&
        return Expr(:struct, is_mutable, sig, Expr(:block, struct_pos...))

    new_call = Expr(:call, :new, all_names...)
    if has_explicit_kw
        ctor_def = Expr(:(=),
            Expr(:call, ctor, Expr(:parameters, map(_unwrap_const, kw_fields)...), map(_unwrap_const, pos_fields)...),
            new_call)
        return Expr(:struct, is_mutable, sig, Expr(:block, [struct_pos; struct_kw]..., ctor_def))
    else
        required = filter(f -> !Meta.isexpr(_unwrap_const(f), :kw), pos_fields)
        optional = filter(f ->  Meta.isexpr(_unwrap_const(f), :kw), pos_fields)
        pos_ctor = Expr(:(=), Expr(:call, ctor, map(_unwrap_const, pos_fields)...), new_call)
        kw_ctor  = Expr(:(=),
            Expr(:call, ctor, Expr(:parameters, map(_unwrap_const, optional)...), map(_unwrap_const, required)...),
            new_call)
        return Expr(:struct, is_mutable, sig, Expr(:block, struct_pos..., pos_ctor, kw_ctor))
    end
end

# Recursively generate abstract type + concrete subtypes for a `Parent > (children...)` hierarchy.
function _types_impl(abstract_expr, subtypes_expr, parent_head=nothing; is_mutable=false, docpath="")
    abstract_name, abstract_params = _terse_parse_type(abstract_expr)
    abstract_head = _build_curly(abstract_name, abstract_params)
    abstract_decl = Expr(:abstract, parent_head === nothing ? abstract_head : Expr(:<:, abstract_head, parent_head))
    current_path = isempty(docpath) ? string(abstract_name) : docpath * " > " * string(abstract_name)

    children = Meta.isexpr(subtypes_expr, :tuple) ? subtypes_expr.args : [subtypes_expr]

    decls = Any[]
    pending_doc = nothing
    for st in children
        if _is_docstr(st)
            pending_doc = st
            continue
        end
        local_mutable, st = _unwrap_mutable(is_mutable, st)
        if Meta.isexpr(st, :call) && st.args[1] == :>
            push!(decls, _types_impl(st.args[2], st.args[3], abstract_head; is_mutable=local_mutable, docpath=current_path))
            pending_doc = nothing
        elseif st isa Symbol
            struct_expr = _make_struct(local_mutable, Expr(:<:, _build_curly(st, abstract_params), abstract_head), Any[])
            doc = something(pending_doc, current_path * " > \n" * _autodoc_sig(st, abstract_params, Any[], Any[]))
            push!(decls, _wrap_doc(doc, struct_expr))
            append!(decls, _show_method_exprs(st))
            pending_doc = nothing
        else
            name, params, pos_fields, kw_fields = _terse_parse_subtype(st)
            struct_expr = _make_struct(local_mutable, Expr(:<:, _build_curly(name, params), abstract_head), pos_fields, kw_fields)
            doc = something(pending_doc, current_path * " > \n" * _autodoc_sig(name, params, pos_fields, kw_fields))
            push!(decls, _wrap_doc(doc, struct_expr))
            append!(decls, _show_method_exprs(name))
            pending_doc = nothing
        end
    end

    is_terse = GlobalRef(Terse, :is_terse_type)
    abstract_trait = Expr(:(=), Expr(:call, is_terse, Expr(:(::), Expr(:curly, :Type, Expr(:(<:), abstract_name)))), true)
    return Expr(:block, abstract_decl, abstract_trait, decls...)
end

# Top-level dispatch: route a single @types expression to the appropriate code generator.
function _types_single(is_mutable, ex)
    is_mutable, ex = _unwrap_mutable(is_mutable, ex)
    if ex isa Symbol || Meta.isexpr(ex, :curly)
        abstract_name, abstract_params = _terse_parse_type(ex)
        return Expr(:abstract, _build_curly(abstract_name, abstract_params))
    elseif Meta.isexpr(ex, :call) && ex.args[1] != :>
        name, params, pos_fields, kw_fields = _terse_parse_subtype(ex)
        struct_expr = _make_struct(is_mutable, _build_curly(name, params), pos_fields, kw_fields)
        return Expr(:block, struct_expr, _show_method_exprs(name)...)
    elseif Meta.isexpr(ex, :<:)
        name, params, pos_fields, kw_fields = _terse_parse_subtype(ex.args[1])
        struct_expr = _make_struct(is_mutable, Expr(:<:, _build_curly(name, params), ex.args[2]), pos_fields, kw_fields)
        return Expr(:block, struct_expr, _show_method_exprs(name)...)
    elseif Meta.isexpr(ex, :call) && ex.args[1] == :>
        return _types_impl(ex.args[2], ex.args[3]; is_mutable)
    end
    error("@types: unrecognised syntax: $ex")
end

#-----------------------------------------------------------------------------# @types
"""
    @types AbstractType
    @types [mutable] ConcreteType(pos_fields...; kw_fields...)
    @types [mutable] ConcreteType(pos_fields...; kw_fields...) <: SuperType
    @types [mutable] AbstractType > (Subtype1(fields...), Subtype2(fields...))
    @types [mutable] AbstractType{T} > (Subtype1{T}(fields...), Subtype2{T, S}(fields...))

Define abstract types, concrete structs, or full type hierarchies in one expression.

- `mutable` makes all generated concrete structs mutable.
- `@mutable SubType(...)` makes an individual subtype mutable within a hierarchy.
- `@const(field::T)` marks a field as const within a `@mutable` or `mutable` type.
- Fields with default values (`field::T = val`) generate inner constructors for both
  positional-with-defaults and keyword argument construction.
- Use `;` to separate positional fields from keyword-only fields, generating a single
  constructor that mirrors the exact positional/keyword split you specify.
- Subtypes can themselves use `>` to define nested hierarchies.
- Bare names (no parentheses) produce zero-field structs inheriting the parent's type parameters.
- Each concrete subtype gets an auto-generated docstring showing its hierarchy path and
  constructor signature (e.g. `"Animal > \nDog(name::String)"`). Place a string literal
  immediately before a subtype entry to override it with a custom docstring.

### Examples

```julia
@types Animal

@types Cat(lives::Int)

@types Dog(name::String) <: Animal

@types mutable Counter(n::Int = 0)

@types Server(host::String; port::Int = 8080, timeout::Int = 30)

@types Animal > (
    Cat(lives::Int),
    Dog(name::String)
)

@types Animal > (
    Cat(lives::Int = 9),
    @mutable Dog(@const(name::String), legs::Int)
)

# Custom docstrings: place a string before the entry to override the auto-generated doc
@types Animal > (
    "A feline with a fixed number of lives.",
    Cat(lives::Int = 9),
    Dog(name::String),  # auto-doc: "Animal > \nDog(name::String)"
)

@types Animal{T} > (
    Cat{T}(lives::Int, family::T),
    Dog{T, S <: AbstractString}(name::S, family::T),
    Invertebrate{T} > (
        Worm,
        Insect{T, I <: Integer}(legs::I, family::T)
    )
)
```
"""
macro types(ex)
    esc(_types_single(false, ex))
end

macro types(mutable_kw, ex)
    mutable_kw === :mutable || error("@types: expected `mutable`, got `$mutable_kw`")
    esc(_types_single(true, ex))
end

end # module
